language: python
python:
  - "2.7"
# command to install dependencies
install:
    - pip install flake8 flake8-respect-noqa pre-commit
# command to run tests
script:
    - make test
#notifications
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=96ea555dfa209291bf11ba8ce5f3e05b0a0ab70549452c7a64150370c68269bf
    #url:
    # － https://oapi.dingtalk.com/robot/send?access_token=96ea555dfa209291bf11ba8ce5f3e05b0a0ab70549452c7a64150370c68269bf
    #on_success: always
